prov_vo/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from . import views
import vosi.views
import vosi.urls

app_name = 'prov_vo'

# add automatically created urls:
router = routers.DefaultRouter()
router.register(r'activities', views.ActivityViewSet)
router.register(r'entities', views.EntityViewSet)
router.register(r'agents', views.AgentViewSet)
router.register(r'used', views.UsedViewSet)
router.register(r'wasgeneratedby', views.WasGeneratedByViewSet)
router.register(r'wasassociatedwith', views.WasAssociatedWithViewSet)
router.register(r'wasattributedto', views.WasAttributedToViewSet)
router.register(r'hadmember', views.HadMemberViewSet)
router.register(r'wasderivedfrom', views.WasDerivedFromViewSet)
router.register(r'collection', views.CollectionViewSet)

urlpatterns = [
    # index view:
    url(r'^$', views.IndexView.as_view(), name='index'),

    # include automatic rest api urls for models
    # do NOT use a namespace here, because cannot have nested namespaces (prov_vo:api:activites-list won't work)
    url(r'^api/', include(router.urls)),

    # serialization of everything:
    url(r'^allprov/(?P<format>[a-zA-Z-]+)$', views.allprov, name='allprov'),
    url(r'^prettyprovn/$', views.prettyprovn, name='prettyprovn'),

    # provdal form
    url(r'^provdal/$', views.provdal, name='provdal'),
    url(r'^provdalform/$', views.provdal_form, name='provdal_form'),
    # vosi endpoints required by dali: capabilities (must be sibling to provdal, Sec. 2 of DALI), availability
    url(r'^availability/$', vosi.views.availability, name='vosi_availability'),
    url(r'^capabilities/$', vosi.views.capabilities, name='vosi_capabilities'),

    # graph overviews
    url(r'^graph/$', views.graph, name='graph'),
    url(r'^graph/graphjson$', views.fullgraphjson, name='graphjson'),

]

prov_vo/templates/prov_vo/activities.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance webapp - Activities{% endblock %}

{% block content %}
<h1>RAVE Activities</h1>

<p>
Following activities are recorded for RAVE. Click on one of them to show the details.
</p>
{% if activity_list %}
    <ul>
    {% for activity in activity_list %}
        <li><a href="{% url 'prov_vo:activity_detail' activity.id %}">{{ activity.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No activities are available.</p>
{% endif %}

{% endblock %}

prov_vo/templates/prov_vo/activity_detail.html
{% extends "prov_vo/base.html" %}

{% block title %}Details for an activity{% endblock %}

{% block content %}

<h2>Activity: {{ activity.label }}</h2>
<h3>Details</h3>
<ul>
<li>id: {{ activity.id }}</li>
<li>name: {{ activity.name }}</li>
<li>type: {{ activity.type }}</li>
<li>annotation: {{ activity.annotation }}</li>
<li>startTime: {{ activity.startTime }}</li>
<li>endTime: {{ activity.endTime }}</li>
</ul>


<h3>Relations</h3>
<h4>Used (input)</h4>
{% if used_list %}
    <ul>
    {% for used in used_list %}
        {% if activity.id in used.activity.id %}
            <li><a href="{% url 'prov_vo:activity_detail' activity.id %}">{{ activity.name }}</a>
                used
                <a href="{% url 'prov_vo:entity_detail' used.entity.id %}">{{ used.entity.name }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p class="notfound">No used relations are available.</p>
{% endif %}


<h4>WasGeneratedBy (output)</h4>
{% if wasGeneratedBy_list %}
    <ul>
    {% for wasGeneratedBy in wasGeneratedBy_list %}
        {% if activity.id in wasGeneratedBy.activity.id %}
            <li><a href="{% url 'prov_vo:entity_detail' wasGeneratedBy.entity.id %}">{{ wasGeneratedBy.entity.name }}</a>
                wasGeneratedBy
                <a href="{% url 'prov_vo:activity_detail' activity.id %}">{{ activity.name }}</a>
                </li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p class="notfound">No wasGeneratedBy relations are available.</p>
{% endif %}


<h4>WasAssociatedWith (contacts, acknowledgements)</h4>
{% if wasAssociatedWith_list %}
    <ul>
    {% for wasAssociatedWith in wasAssociatedWith_list %}
        {% if activity.id in wasAssociatedWith.activity.id %}
            <li><a href="{% url 'prov_vo:activity_detail' activity.id %}">{{ activity.name }}</a>
                wasAssociatedWith
                <a href="{% url 'prov_vo:agent_detail' wasAssociatedWith.agent.id %}">{{ wasAssociatedWith.agent.name }}</a>
                </li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p class="notfound">No agent relations are available.</p>
{% endif %}


<h3>Graphs</h3>
<div id="url_graphjson" class="hidden">{{ url }}</div>

<h4>Sankey chart</h4>
<p>Based on <a href="https://bost.ocks.org/mike/sankey/">https://bost.ocks.org/mike/sankey/</a>.
</p>

<p id="chart"></p>
<aside>Drag to rearrange nodes.</aside>

<h4>Force directed graph layout</h4>
<p>See e.g. <a href="http://bl.ocks.org/mbostock/4062045">http://bl.ocks.org/mbostock/4062045</a> for an example.

<p id="force-legend"></p>

<p id="force-graph"></p>

{% load staticfiles %}
<script src="{% static 'prov_vo/provgraphs.js' %}" charset="utf-8"></script>

{% endblock %}

prov_vo/templates/prov_vo/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
<meta charset="utf-8"/>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'prov_vo/bootstrap.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'prov_vo/style.css' %}" >
<!-- <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script> -->
<script src="{% static 'prov_vo/d3.v3.min.js' %}" charset="utf-8" type="text/javascript"></script>
<script src="{% static 'prov_vo/sankey.js' %}" type="text/javascript"></script>


<title>{% block title %}{% endblock %}</title>

<script type="text/javascript">
{% block javascript %}{% endblock %}
</script>

</head>
<body>

<div class="container-fluid">
{% block content %}{% endblock %}
</div>

<div style="clear:both"></div>
<p class="footer">django-prov_vo &ndash; Implementing the IVOA Provenance Data Model</p>
</body>
</html>

prov_vo/templates/prov_vo/graph.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance graph{% endblock %}

{% block content %}

<h2>Provenance of RAVE data DR4</h2>

<h3>Graphical representations of everything</h3>
<div id="url_graphjson" class="hidden">{{ url }}</div>

<h4>Sankey chart</h4>
<p>Based on <a href="https://bost.ocks.org/mike/sankey/">https://bost.ocks.org/mike/sankey/</a>.
</p>

<p id="chart"></p>
<aside>Drag to rearrange nodes.</aside>

<br>

<h4>Force directed graph layout</h4>
<p>See e.g. <a href="http://bl.ocks.org/mbostock/4062045">http://bl.ocks.org/mbostock/4062045</a> for an example.

<p id="force-legend"></p>

<p id="force-graph"></p>

{% load staticfiles %}
<script src="{% static 'prov_vo/provgraphs.js' %}" charset="utf-8"></script>

{% endblock %}

prov_vo/templates/prov_vo/index.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance VO{% endblock %}

{% block content %}
<h1>IVOA ProvenanceDM implementation</h1>
<p>
    This is a prototype webapp for displaying provenance information for astronomical datasets, using the <a href="https://www.djangoproject.com/">Django framework</a>. It implements the <a href="http://volute.g-vo.org/svn/trunk/projects/dm/provenance/description/ProvenanceDM.pdf">ProvenanceDM</a> data model currently discussed in the IVOA, which is based on the W3C ProvDM data model.
</p>

<h4>ProvenanceDM Data Access Layer (ProvDAL)</h4>
The ProvDAL endpoint is located at <a href="{% url 'prov_vo:provdal' %}">{% url 'prov_vo:provdal' %}</a>. It takes following possible request parameters:
<ul>
    <li>ID: a valid identifier for an entity or activity</li>
    <li>DEPTH: integer for the number of steps to track provenance history or <code>ALL</code> for everything</li>
    <li>DIRECTION: the direction in which to track processing steps/data flow, either <code>BACK</code> (default) or <code>FORTH</code></li>
    <li>MODEL: <code>IVOA</code> for compliance with IVOA ProvenanceDM or <code>W3C</code> for compliance with W3C ProvDM</li>
    <li>RESPONSEFORMAT: only <code>PROV-JSON</code> and <code>PROV-N</code> are possible for now, in addition: <code>Graphics</code></li>
    <li>MEMBERS: set to <code>true</code> if hadMember relations of collections shall be tracked as well, default: <code>false</code></li>
    <li>STEPS: set to <code>true</code> if hadStep relations of activityFlows shall be tracked as well, default: <code>false</code></li>
    <li>AGENT: set to <code>true</code> if relations from an agent to other activities and entities shall be tracked as well, default: <code>false</code></li>
</ul>

There is also a <a href="{% url 'prov_vo:provdal_form' %}">ProvDAL Form</a> which you can fill out and submit, so it will create and send the appropriate request for you.

The corresponding VOSI resources for ProvDAL are:
<ul>
    <li><a href="{% url 'prov_vo:vosi_availability' %}">{% url 'prov_vo:vosi_availability' %}</a></li>
    <li><a href="{% url 'prov_vo:vosi_capabilities' %}">{% url 'prov_vo:vosi_capabilities' %}</a></li>
</ul>


<h4>Forms</h4>
<ul>
    <li>ProvenanceDM Data Access Layer: <a href="{% url 'prov_vo:provdal_form' %}">Form for ProvDAL</a></li>
</ul>

<h4>Complete provenance (overview)</h4>
<ul>
    <li>Overview: <a href="{% url 'prov_vo:graph' %}">Graph</a> of the main workflow (ignoring ActivityFlow and wasInformedBy)</li>
    <li>Overview: <a href="{% url 'prov_vo:allprov' 'PROV-N' %}">PROV-N</a> or <a href="{% url 'prov_vo:allprov' 'PROV-JSON' %}">PROV-JSON</a> representation</li>
    <li>Overview: <a href="{% url 'prov_vo:prettyprovn' %}">Pretty Provn</a> representation (with clickable links, not complete)</li>
</ul>


<h4>REST API</h4>
<p>
    Pick one of the classes below to show the available data using the REST
    <a href="{% url 'prov_vo:api-root' %}">api</a>:
</p>
<ul>
    <li><a href="{% url 'prov_vo:activity-list' %}">Activity</a></li>
    <li><a href="{% url 'prov_vo:entity-list' %}">Entity</a></li>
    <li><a href="{% url 'prov_vo:agent-list' %}">Agent</a></li>
</ul>

<p>
    Append the id of a specific record to get its details.
    (In principle one can also add new records and update or delete existing ones, but this is not tested, yet.)
</p>
<ul>
    <li>details: <a href="{% url 'prov_vo:activity-detail' 'rave:act_dataextraction' %}">{% url 'prov_vo:activity-detail' 'rave:act_dataextraction' %}</a></li>
</ul>

<p>
    For one activity, a normal json representation is shown by appending
    <code>?format=json</code> to the existing detail url, e.g.:
</p>
    <ul>
         <li>json: <a href="{% url 'prov_vo:activity-detail' 'rave:act_dataextraction' %}?format=json">/prov_vo/activities/rave:act_dataextraction/?format=json/</a></li>
    </ul>
<p>
    xml and provn serialisations still need to be defined, e.g. like this <code>?format=xml</code>
</p>


<h4>Sources</h4>
<p>
    The sources for this web application are available at <a href="https://github.com/kristinriebe/django-prov_vo/">GitHub: kristinriebe/django-prov_vo</a>.
</p>
{% endblock %}

prov_vo/templates/prov_vo/provdal_graph.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance graph{% endblock %}

{% block content %}

<h3>Graphical representation</h3>
These graphs are generated using javascript (see references at the bottom of this page). The required json structure of provenance information was retrieved via this URL:<br>
<a href="{{ url }}">{{ url }}</a>.

<h4>Sankey chart</h4>

<div id="url_graphjson" class="hidden">{{ url }}</div>
<p id="chart">
</p>
<aside>Drag to rearrange nodes.</aside>

<br>

<h4>Force directed graph layout</h4>

<p id="force-legend"></p>

<p id="force-graph"></p>


<p>
	 The sankey chart is based on <a href="https://bost.ocks.org/mike/sankey/">https://bost.ocks.org/mike/sankey/</a>, the force directed graph layout was derived from the example at <a href="http://bl.ocks.org/mbostock/4062045">http://bl.ocks.org/mbostock/4062045</a>.
</p>

{% load staticfiles %}
<script src="{% static 'prov_vo/provgraphs.js' %}" charset="utf-8"></script>

{% endblock %}

prov_vo/templates/prov_vo/provdalform.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance search{% endblock %}

{% block content %}

<h2>Provenance Data Access Layer (ProvDAL)</h2>

<div class="row">
  <div class="col-md-6">
    Put an identifier of an entity or activity in the field below and submit for retrieving the provenance record (backwards in time). If you want provenance information for an agent, enter its ID and additionally check the Agent option.
    You can check the list of available <a href="{% url 'prov_vo:entity-list' %}">entities</a>, <a href="{% url 'prov_vo:activity-list' %}">activities</a> and <a href="{% url 'prov_vo:agent-list' %}">agents</a> for valid IDs.
  </div>
</div>
<hr>
<form action="{% url 'prov_vo:provdal_form' %}" method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}
  <div class="row">
    <div class="col-md-2">
          <strong>{{ field.label }}</strong>
    </div>
    <div class="col-md-5">
          {{ field }}
      <div style="clear: both"></div>
      <div>
        <span class="helptext">{{ field.help_text }}</span>
          {{ field.errors }}
      </div>
    </div>
  </div>
    {% endfor %}
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-5">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>

{% endblock %}

prov_vo/templates/prov_vo/provn.html
{% extends "prov_vo/base.html" %}

{% block title %}Provenance webapp - PROV-N output{% endblock %}

{% block content %}
<h1>PROV-N serialization with links</h1>


<div>
{% if activity_list %}
    {% for activity in activity_list %}
        <span class="activity">activity</span>( <a href="{% url 'prov_vo:activity-detail' activity.id %}">{{ activity.id }}</a>, 
        {{ activity.startTime }}, 
        {{ activity.endTime }}, 
        [prov:type = '{{ activity.type }}', 
         prov:name = '{{ activity.name }}', 
         prov:annotation = '{{ activity.annotation }}'
        ] )
        <br>
    {% endfor %}
{% endif %}
{% if entity_list %}
    {% for entity in activity_list %}
        <span class="entity">entity</span>( <a href="{% url 'prov_vo:entity-detail' entity.id %}">{{ entity.id }}</a>, 
        [prov:type = '{{ entity.type }}', 
         prov:name = '{{ entity.name }}', 
         prov:annotation = '{{ entity.annotation }}'
        ] )
        <br>
    {% endfor %}
{% endif %}
{% if agent_list %}
    {% for ag in agent_list %}
        <span class="agent">agent</span>( <a href="{% url 'prov_vo:agent-detail' ag.id %}">{{ ag.id }}</a>, 
        [prov:type = '{{ ag.type }}', 
         prov:name = '{{ ag.name }}', 
         prov:annotation = '{{ ag.annotation }}'
        ] )
        <br>
    {% endfor %}
{% endif %}
{% if used_list %}
    {% for u in used_list %}
        <span class="used">used</span>( <a href="{% url 'prov_vo:activity-detail' u.activity.id %}">{{ u.activity.id }}</a>, 
        <a href="{% url 'prov_vo:entity-detail' u.entity.id %}">{{ u.entity.id }}</a>
        [id = '{{ u.id }}, prov:role = '{{ u.role }}'] )
        <br>
    {% endfor %}
{% endif %}
{% if wasGeneratedBy_list %}
    {% for w in wasGeneratedBy_list %}
        <span class="wasGeneratedBy">wasGeneratedBy</span>( <a href="{% url 'prov_vo:entity-detail' w.entity.id %}">{{ w.entity.id }}</a>,
         <a href="{% url 'prov_vo:activity-detail' w.activity.id %}">{{ w.activity.id }}</a>, 
        [id = '{{ w.id }}, prov:role = '{{ w.role }}'] )
        <br>
    {% endfor %}
{% endif %}
{% if wasAssociatedWith_list %}
    {% for w in wasAssociatedWith_list %}
        <span class="wasAssociatedWith">wasAssociatedWith</span>( <a href="{% url 'prov_vo:activity-detail' w.activity.id %}">{{ w.activity.id }}</a>, 
        <a href="{% url 'prov_vo:agent-detail' w.agent.id %}">{{ w.agent.id }}</a>, 
        [id = '{{ w.id }}, prov:role = '{{ w.role }}'] )
        <br>
    {% endfor %}
{% endif %}
{% if wasAttributedTo_list %}
    {% for w in wasAttributedTo_list %}
        <span class="wasAttributedTo">wasAttributedTo</span>( <a href="{% url 'prov_vo:entity-detail' w.entity.id %}">{{ w.entity.id }}</a>,
        <a href="{% url 'prov_vo:agent-detail' w.agent.id %}">{{ w.agent.id }}</a>,
        [id = '{{ w.id }}, prov:role = '{{ w.role }}'] )
        <br>
    {% endfor %}
{% endif %}
</div>




{% endblock %}